categories = {
    'Блоги': '/blogs',
    'Новости и СМИ': '/news',
    'Юмор и развлечения': '/entertainment',
    'Технологии': '/tech',
    'Экономика': '/economics',
    'Бизнес и стартапы': '/business',
    'Криптовалюты': '/crypto',
    'Путешествия': '/travels',
    'Маркетинг, PR, реклама': '/marketing',
    'Психология': '/psychology',
    'Дизайн': '/design',
    'Политика': '/politics',
    'Искусство': '/art',
    'Право': '/law',
    'Образование': '/education',
    'Книги': '/books',
    'Лингвистика': '/language',
    'Карьера': '/career',
    'Познавательное': '/edutainment',
    'Курсы и гайды': '/courses',
    'Спорт': '/sport',
    'Мода и красота': '/beauty',
    'Медицина': '/medicine',
    'Здоровье и Фитнес': '/health',
    'Картинки и фото': '/pics',
    'Софт и приложения': '/apps',
    'Видео и фильмы': '/video',
    'Музыка': '/music',
    'Игры': '/games',
    'Еда и кулинария': '/food',
    'Цитаты': '/quotes',
    'Рукоделие': '/handmade',
    'Семья и дети': '/babies',
    'Природа': '/nature',
    'Интерьер и строительство': '/construction',
    'Telegram': '/telegram',
    'Инстаграм': '/instagram',
    'Продажи': '/sales',
    'Транспорт': '/transport',
    'Религия': '/religion',
    'Эзотерика': '/esoterics',
    'Даркнет': '/darknet',
    'Букмекерство': '/gambling',
    'Шок-контент': '/shock',
    'Эротика': '/erotica',
    'Для взрослых': '/adult',
    'Другое': '/other'}

base_url = "https://tgstat.ru"